qtool: vpnc-dial-in: stop if vpnc fails
Signed-off-by: Peter Xu <peterx@redhat.com>

diff --git a/rh/qtool b/rh/qtool
--- a/rh/qtool
+++ b/rh/qtool
@@ -1168,10 +1168,16 @@ do_vpnc_dial_in()
     done
 
     $vpnc_cmd
+    if [[ $? != 0 ]]; then
+        echo "VPN connection failed."
+        return 1
+    fi
 
     sleep 1
     echo "Re-starting offlineimap service..."
     pkill -9 -f /usr/bin/offlineimap
+
+    return 0
 }
 
 cmd=$1
