qtool: add auto_apply sub-command
This command could help me to apply list of patches easily.

Signed-off-by: Peter Xu <peterx@redhat.com>

diff --git a/rh/qtool b/rh/qtool
--- a/rh/qtool
+++ b/rh/qtool
@@ -14,6 +14,8 @@ init-dev:      init dev environment for host
 build-initrd:  build initrd.img from directory
 kernel-run:    run specific kernel using QEMU
 kernel-quit:   stop the running kernel...
+auto-apply:    apply patche list automatically
+
 EOF
     exit 1
 }
@@ -163,14 +165,58 @@ do_kernel_quit ()
     pkill -f "$prog_name kernel-run"
 }
 
+do_auto_apply()
+{
+    patches="$@"
+    count=0
+    if [[ -z "$patches" ]]; then
+        echo "usage: auto_apply <patch1> [patch2 [patch3 ...]]"
+        echo
+        echo "This will do the following:"
+        echo "  1. Try apply patch locally (try -p0 then -p1)"
+        echo "  2. Commit the patch using git"
+        echo
+        echo "Will stop when failed to apply a patch"
+        echo
+        echo "Example: # qtool auto_apply /root/rpmbuild/SOURCES/*.patch"
+        return 1
+    fi
+    for patch in $patches; do
+        applied=false
+        if [[ $patch != /* ]]; then
+            echo "Please provide patch full path for $patch"
+            return 1
+        fi
+        for level in 1 0; do
+            patch -t -p$level < $patch
+            if [[ $? == 0 ]]; then
+                applied=true
+                break
+            fi
+        done
+        if ! $applied; then
+            echo "patch '$patch' failed to apply, stop here."
+            return 1
+        fi
+        # TODO: when there are new files, I'd better detect it and
+        # commit too.
+        git commit -a -m "Apply patch $(basename $patch)"
+        count=$(( $count + 1 ))
+    done
+    echo "All $count patches applied successfully."
+    echo "Please service yourself to cleanup *.orig."
+}
+
 cmd=$1
+shift 1
 
 case $cmd in
     qemu-build) do_qemu_build ;;
-    init-dev) do_init_dev $2 ;;
-    build-initrd) do_build_initrd $2 ;;
+    init-dev) do_init_dev $1 ;;
+    build-initrd) do_build_initrd $1 ;;
     kernel-run) do_kernel_run ;;
     kernel-quit) do_kernel_quit ;;
+    auto-apply) do_auto_apply $@ ;;
     *)
         usage ;;
 esac
