update rh_fetch_pkg
Signed-off-by: Peter Xu <peterx@redhat.com>

diff --git a/rh/rh_fetch_pkg b/rh/rh_fetch_pkg
--- a/rh/rh_fetch_pkg
+++ b/rh/rh_fetch_pkg
@@ -1,82 +1,55 @@
-#!/usr/bin/python
+#!/bin/bash
 
-import sys
-import ssl
-import json
-import urllib2
-from sgmllib import SGMLParser
+prog="$0"
+task_url="$1"
+version="$2"
 
-prog_name = sys.argv[0]
-prm_arch = "x86_64"
-prm_suffix = ".rpm"
-prm_suffix_len = len(prm_suffix)
-url_template = "https://brewweb.devel.redhat.com/buildinfo?buildID=%(brew_id)s"
-help_msg = """
-usage: %(prog)s <brew_build_id>
-
-Fetch packages from Brew with specific requirements:
-
-Arch:   %(arch)s
-Suffix: %(suffix)s
-""" % {
-    "prog": prog_name,
-    "arch": prm_arch,
-    "suffix": prm_suffix,
+err()
+{
+    echo "ERROR: $@"
+    exit 1
 }
 
-def usage ():
-    print help_msg
-    sys.exit(1)
+usage()
+{
+    echo "Usage:"
+    echo
+    echo "  $prog <task_url> <version>"
+    echo
+    exit 1
+}
 
-def url_get (url):
-    gcontext = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
-    sock = urllib2.urlopen(url, context=gcontext)
-    html = sock.read()
-    sock.close()
-    return html
+[[ -n "$task_url" ]] || usage
+[[ -n "$version" ]] || usage
 
-def url_download (url):
-    fname = url[url.rfind("/") + 1:]
-    print "Downloading file %s" % url
-    sock_in = urllib2.urlopen(url)
-    out = open(fname, "wb")
-    out.write(sock_in.read())
-    sock_in.close()
-    out.close()
-    print "File %s downloaded" % fname
+file_list="
+qemu-guest-agent-${version}.rpm
+qemu-img-${version}.rpm
+qemu-guest-agent-debuginfo-${version}.rpm
+qemu-img-debuginfo-${version}.rpm
+qemu-kiwi-${version}.rpm
+qemu-kiwi-debuginfo-${version}.rpm
+qemu-kvm-${version}.rpm
+qemu-kvm-block-curl-${version}.rpm
+qemu-kvm-block-curl-debuginfo-${version}.rpm
+qemu-kvm-block-gluster-${version}.rpm
+qemu-kvm-block-gluster-debuginfo-${version}.rpm
+qemu-kvm-block-iscsi-${version}.rpm
+qemu-kvm-block-iscsi-debuginfo-${version}.rpm
+qemu-kvm-block-rbd-${version}.rpm
+qemu-kvm-block-rbd-debuginfo-${version}.rpm
+qemu-kvm-block-ssh-${version}.rpm
+qemu-kvm-block-ssh-debuginfo-${version}.rpm
+qemu-kvm-common-${version}.rpm
+qemu-kvm-common-debuginfo-${version}.rpm
+qemu-kvm-core-${version}.rpm
+qemu-kvm-core-debuginfo-${version}.rpm
+qemu-kvm-debuginfo-${version}.rpm
+qemu-kvm-debugsource-${version}.rpm
+"
 
-class PkgUrlParser (SGMLParser):
-    def reset (self):
-        SGMLParser.reset(self)
-        self.urls = []
-
-    def start_a (self, attrs):
-        href = [v for k, v in attrs if k == 'href' \
-                and v[0:4] == "http"] 
-        self.urls.extend(href)
-
-def brew_fetch_urls (brew_id):
-    global prm_suffix, prm_suffix_len, prm_arch
-    parser = PkgUrlParser()
-    url = url_template % {"brew_id": brew_id}
-    print "Parsing brew link: %s" % url
-    parser.feed(url_get(url))
-    # only keep ARCH specific packages
-    urls = filter(lambda x: x.find(prm_arch) != -1, parser.urls)
-    # only keep RPM links rather than else
-    return filter(lambda x: x[-prm_suffix_len:] == prm_suffix, urls)
-    
-if len(sys.argv) != 2:
-    usage()
-
-brew_id = sys.argv[1]
-if not brew_id.isdigit():
-    print "Brew ID incorrect: %s" % brew_id
-    usage()
-
-count = 0
-urls = brew_fetch_urls(brew_id)
-for url in urls:
-    url_download(url)
-    count += 1
-print "Totally %s file downloaded" % count
+for f in $file_list; do
+    url="$task_url/$f"
+    echo "Downloading file: $f"
+    wget $url
+done
